### ISSUE TITLE
hOW CAN I GeT This  License And  RAR password ?

### ISSUE THREAD

**Issue by Gopnitsa** [bytecode77/self-morphing-csharp-binary#2]
hOW CAN I GeT This  License And  RAR password ? Can you help me or are you selling this. İf you selling this project iwant to buy .

**Comment by bytecode77** [comment]
I had this same question a couple of times... The password is written right next to the download link itself.

The only reason I encrypt the downloads is so that my website doesn't get flagged as malicious by search engines.
